# Autogenerated wrapper script for libsparseir_jll for aarch64-linux-gnu-cxx03
export libsparseir

using CompilerSupportLibraries_jll
using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("libsparseir")
JLLWrappers.@declare_library_product(libsparseir, "libsparseir.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libsparseir,
        "lib/libsparseir.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
