# Autogenerated wrapper script for libsparseir_jll for powerpc64le-linux-gnu
export libsparseir

using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("libsparseir")
JLLWrappers.@declare_library_product(libsparseir, "libsparse_ir_capi.so")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libsparseir,
        "lib/libsparse_ir_capi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
