# Autogenerated wrapper script for libsparseir_jll for x86_64-w64-mingw32
export libsparseir

using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("libsparseir")
JLLWrappers.@declare_library_product(libsparseir, "libsparse_ir_capi.dll")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libsparseir,
        "bin\\libsparse_ir_capi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
